# Generated by Django 4.2 on 2025-01-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0006_auto_20200724_0909"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockrecord",
            name="cost_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Cost Price",
            ),
        ),
    ]
